require_relative 'pieces/piece.rb'
require_relative 'pieces/Queen.rb'
require_relative 'pieces/King.rb'
require_relative 'pieces/Bishop.rb'
require_relative 'pieces/Knight.rb'
require_relative 'pieces/Rook.rb'
require_relative 'pieces/Pawn.rb'
